### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Newinvestcoin** [johannesmols/BitcoinRpcMiner#1]
hi! how install scrypt?
i have python, do pip install, but what database need and where i need set server, base, user, pass?

**Comment by johannesmols** [comment]
Hey, thank you for your interest! I didn't expect anyone to find this.
I just pushed a commit with an SQL script to create the necessary tables. It is made for PostgreSQL.
I also updated the config file to include the variables to set up a database connection.
Be aware that this will take a very long time to collect all data due to how slow the Bitcoin RPC can be. It might take multiple weeks.
It is also quite specific for analysis purposes. If you just need a list of all OP_RETURN transactions I'd recommend a different approach (I can show you how).
